export default {
  id: { type: String },
  leadingIcon: { type: String },
  trailingIcon: { type: String },
  labelInfo: { type: String },
  trailingText: { type: String },
  state: { type: Boolean },
  coutable: { type: Boolean },
  loading: { type: Boolean },
  last: { type: Boolean },
  float: { type: Boolean },
  disabled: { type: Boolean },
  invalidFeedback: { type: String },
  autofocus: { type: Boolean },
  size: { type: [String, Number] },
  label: { type: String },
};
