name: 'Publish NPM'

on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC
  contents: read

env:
  NODE_VERSION: 20.x

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
          scope: '@tray-tecnologia'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
      - uses: actions/upload-artifact@v4
        with:
          name: ds-build
          path: dist/
